In [1]:
import pandas as pd

In [41]:
pd.set_option("display.max_columns", None)

In [42]:
df = pd.read_csv("invent2.csv", delimiter=';',sep='\t', header=0, engine='python',date_parser=['PeriodoPluviometroFim'])

In [43]:
df.columns

Index(['RegistroID', 'Importado', 'Temporario', 'Removido',
       'ImportadoRepetido', 'BaciaCodigo', 'SubBaciaCodigo', 'RioCodigo',
       'EstadoCodigo', 'MunicipioCodigo', 'ResponsavelCodigo',
       'ResponsavelUnidade', 'ResponsavelJurisdicao', 'OperadoraCodigo',
       'OperadoraUnidade', 'OperadoraSubUnidade', 'TipoEstacao', 'Codigo',
       'Nome', 'CodigoAdicional', 'Latitude', 'Longitude', 'Altitude',
       'AreaDrenagem', 'TipoEstacaoEscala', 'TipoEstacaoRegistradorNivel',
       'TipoEstacaoDescLiquida', 'TipoEstacaoSedimentos',
       'TipoEstacaoQualAgua', 'TipoEstacaoPluviometro',
       'TipoEstacaoRegistradorChuva', 'TipoEstacaoTanqueEvapo',
       'TipoEstacaoClimatologica', 'TipoEstacaoPiezometria',
       'TipoEstacaoTelemetrica', 'PeriodoEscalaInicio', 'PeriodoEscalaFim',
       'PeriodoRegistradorNivelInicio', 'PeriodoRegistradorNivelFim',
       'PeriodoDescLiquidaInicio', 'PeriodoDescLiquidaFim',
       'PeriodoSedimentosInicio', 'PeriodoSedimentosFim',
       'PeriodoQualAguaInicio', 'PeriodoQualAguaFim',
       'PeriodoPluviometroInicio', 'PeriodoPluviometroFim',
       'PeriodoRegistradorChuvaInicio', 'PeriodoRegistradorChuvaFim',
       'PeriodoTanqueEvapoInicio', 'PeriodoTanqueEvapoFim',
       'PeriodoClimatologicaInicio', 'PeriodoClimatologicaFim',
       'PeriodoPiezometriaInicio', 'PeriodoPiezometriaFim',
       'PeriodoTelemetricaInicio', 'PeriodoTelemetricaFim', 'TipoRedeBasica',
       'TipoRedeEnergetica', 'TipoRedeNavegacao', 'TipoRedeCursoDagua',
       'TipoRedeEstrategica', 'TipoRedeCaptacao', 'TipoRedeSedimentos',
       'TipoRedeQualAgua', 'TipoRedeClasseVazao', 'UltimaAtualizacao',
       'Operando', 'NumImagens', 'DataIns', 'DataAlt', 'RespAlt'],
      dtype='object')

In [53]:
df[['PeriodoPluviometroFim']] = pd.to_datetime(df['PeriodoPluviometroFim'])
df[['UltimaAtualizacao']] = pd.to_datetime(df['UltimaAtualizacao'])

In [54]:
df.head()

,RegistroID,Importado,Temporario,Removido,ImportadoRepetido,BaciaCodigo,SubBaciaCodigo,RioCodigo,EstadoCodigo,MunicipioCodigo,ResponsavelCodigo,ResponsavelUnidade,ResponsavelJurisdicao,OperadoraCodigo,OperadoraUnidade,OperadoraSubUnidade,TipoEstacao,Codigo,Nome,CodigoAdicional,Latitude,Longitude,Altitude,AreaDrenagem,TipoEstacaoEscala,TipoEstacaoRegistradorNivel,TipoEstacaoDescLiquida,TipoEstacaoSedimentos,TipoEstacaoQualAgua,TipoEstacaoPluviometro,TipoEstacaoRegistradorChuva,TipoEstacaoTanqueEvapo,TipoEstacaoClimatologica,TipoEstacaoPiezometria,TipoEstacaoTelemetrica,PeriodoEscalaInicio,PeriodoEscalaFim,PeriodoRegistradorNivelInicio,PeriodoRegistradorNivelFim,PeriodoDescLiquidaInicio,PeriodoDescLiquidaFim,PeriodoSedimentosInicio,PeriodoSedimentosFim,PeriodoQualAguaInicio,PeriodoQualAguaFim,PeriodoPluviometroInicio,PeriodoPluviometroFim,PeriodoRegistradorChuvaInicio,PeriodoRegistradorChuvaFim,PeriodoTanqueEvapoInicio,PeriodoTanqueEvapoFim,PeriodoClimatologicaInicio,PeriodoClimatologicaFim,PeriodoPiezometriaInicio,PeriodoPiezometriaFim,PeriodoTelemetricaInicio,PeriodoTelemetricaFim,TipoRedeBasica,TipoRedeEnergetica,TipoRedeNavegacao,TipoRedeCursoDagua,TipoRedeEstrategica,TipoRedeCaptacao,TipoRedeSedimentos,TipoRedeQualAgua,TipoRedeClasseVazao,UltimaAtualizacao,Operando,NumImagens,DataIns,DataAlt,RespAlt
0,20545,0,0,0,0,9,90,NaN,66,66000000,906,NaN,NaN,906,NaN,NaN,2,1373001,HUANCARAMA,156243,"-13,65","-73,0833",2765,NaN,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1999-06-05,0,0,31/01/2020,NaN,6
1,20546,0,0,0,0,9,90,NaN,66,66000000,906,NaN,NaN,906,NaN,NaN,2,1373002,SAN MIGUEL,110666,"-13,0167","-73,9833",2661,NaN,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1999-06-05,0,0,31/01/2020,NaN,6
2,20547,0,0,0,0,9,90,NaN,66,66000000,906,NaN,NaN,906,NaN,NaN,2,1373004,ANDAHUAYLAS,110669,"-13,65","-73,3667",2944,NaN,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1999-06-05,0,0,31/01/2020,NaN,6
3,20548,0,0,0,0,9,90,NaN,66,66000000,906,NaN,NaN,906,NaN,NaN,2,1373005,PAMPAS,156217,"-13,4333","-73,8333",2032,NaN,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1999-06-05,0,0,31/01/2020,NaN,6
4,20549,0,0,0,0,9,90,NaN,66,66000000,906,NaN,NaN,906,NaN,NaN,2,1373006,VILCASHUAMAN,156211,"-13,65","-73,95",3150,NaN,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1999-06-05,0,0,31/01/2020,NaN,6

In [39]:
df.loc[df['PeriodoPluviometroFim'].notnull(), 'PeriodoPluviometroFim']

74      1998-01-12
83      1979-01-12
168     1996-01-01
294     1999-01-12
460     2019-01-12
           ...
36360   1983-01-04
36368   1989-01-04
36404   2006-01-03
36412   2012-01-12
36422   1975-01-11
Name: PeriodoPluviometroFim, Length: 6203, dtype: datetime64[ns]

In [60]:
df.loc[df['UltimaAtualizacao'] > '2019', ['UltimaAtualizacao', 'Codigo']]

      UltimaAtualizacao    Codigo
409          2020-01-30    339045
410          2019-03-12   1649000
411          2019-03-12   1655001
412          2019-11-28   2141014
416          2019-11-28   2753006
...                 ...       ...
36034        2019-03-21     48000
36077        2019-09-05   2248135
36094        2019-03-21   8161000
36159        2019-08-14  15172000
36317        2019-03-29   2749056

[3640 rows x 2 columns]